services:
#  mongodb:
#    image: 'mongo:latest'
#    environment:
#      - 'MONGO_INITDB_DATABASE=mydatabase'
#      - 'MONGO_INITDB_ROOT_PASSWORD=secret'
#      - 'MONGO_INITDB_ROOT_USERNAME=root'
#    ports:
#      - '27017'
  graphql:
    build:
      context: .
      dockerfile: Dockerfile
    image: 'graphql/learn:latest'
    ports:
      - '8080:8080'
#    volumes:
#      - .:/app